# Generated by Django 6.0.1 on 2026-04-16 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faculty_department',
            field=models.CharField(choices=[('SCIENCE', 'Faculty of Science'), ('ENGINEERING', 'Faculty of Engineering'), ('BUSINESS', 'Faculty of Business & Economics'), ('EDUCATION', 'Faculty of Education & Community Studies'), ('ARTS', 'Faculty of Arts & Social Sciences'), ('AGRICULTURE', 'Faculty of Agriculture'), ('VET', 'Faculty of Veterinary Medicine & Surgery'), ('ENVIRONMENT', 'Faculty of Environment & Resources Development')], max_length=50),
        ),
    ]
