# Generated by Django 6.0.1 on 2026-02-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('faculty', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('type_of_need', models.CharField(max_length=255)),
                ('explanation', models.TextField(max_length=1000)),
                ('financial_aid_status', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('in_progress', 'In progress')], default='no', max_length=20)),
                ('proof_document', models.FileField(blank=True, null=True, upload_to='support_proofs/')),
                ('referee_full_name', models.CharField(blank=True, max_length=255)),
                ('referee_registration_number', models.CharField(blank=True, max_length=50)),
                ('referee_faculty', models.CharField(blank=True, max_length=255)),
                ('confirm_student_status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
