# Generated by Django 6.0.1 on 2026-03-30 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_club_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.CharField(choices=[('sports', 'Sports'), ('religious', 'Religious'), ('courses', 'Course-Based'), ('others', 'Others')], default='others', max_length=50),
        ),
    ]
