# Generated by Django 6.0.1 on 2026-03-30 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_clubimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
